import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthGuard, AuthProvider } from "@/lib/auth";
import { ThemeProvider } from "@/components/ThemeProvider/page";
import { AntdProvider } from "@/components/AntdProvider/page";
import { App } from "antd";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <AuthProvider>
          <ThemeProvider>
            <AntdProvider>
              <App>
                {children}
              </App>
            </AntdProvider>
          </ThemeProvider>
        </AuthProvider>
       
      </body>
      
      
    </html>
  );
}
